name: Android CI

on:
  push:
    branches: [ "release-setup" ]
  pull_request:
    branches: [ "release-setup" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up signing keys
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > ${{ github.workspace }}/my-release-key.jks
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

    - name: Build APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Rename APK file
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/lost-cities-calculator.apk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: lost-cities-calculator
        path: app/build/outputs/apk/release/lost-cities-calculator.apk
    
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Git Tag
      run: |
        git tag -a 0.0.2 -m "Release version 0.0.2"
        git push origin 0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release and Upload APK
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 0.0.2
        files: ./app/build/outputs/apk/release/lost-cities-calculator.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
