name: Android CI

on:
  push:
    branches: [ "release-setup" ]
  pull_request:
    branches: [ "release-setup" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up signing keys
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > ${{ github.workspace }}/my-release-key.jks
      env:
        KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks

    # - name: Build with Gradle
    #   run: ./gradlew build
    #   env:
    #     KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks
    #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Build APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Rename APK file
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/lost-cities-calculator.apk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: lost-cities-calculator
        path: app/build/outputs/apk/release/lost-cities-calculator.apk


  release:
      runs-on: ubuntu-latest
      needs: build

      steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: lost-cities-calculator

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: ./lost-cities-calculator/lost-cities-calculator.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}