name: Android CI

on:
  push:
    branches: [ "release-notes-v2" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up signing keys
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > ${{ github.workspace }}/my-release-key.jks
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

    # - name: Build APK
    #   run: ./gradlew assembleRelease
    #   env:
    #     KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks
    #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    # - name: Rename APK file
    #   run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/lost-cities-calculator.apk

    # - name: Upload APK as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: lost-cities-calculator
    #     path: app/build/outputs/apk/release/lost-cities-calculator.apk

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fetch Latest Tag
      id: fetch_tag
      run: |
        git fetch --tags
        LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Increment Version
      id: increment_version
      run: |
        MAJOR=${{ vars.MAJOR_VERSION }}
        MINOR=${{ vars.MINOR_VERSION }}
        TAG=${{ env.LATEST_TAG }}
        if [ -z "$TAG" ]; then
          TAG="v0.0.0"
        fi
        TAG=${TAG#v}
        CURRENT_MAJOR=${TAG%%.*}
        CURRENT_MINOR=${TAG#*.}
        CURRENT_MINOR=${CURRENT_MINOR%%.*}
        PATCH=${TAG##*.}

        # Reset patch version if major or minor versions change
        if [ "$MAJOR" -ne "$CURRENT_MAJOR" ] || [ "$MINOR" -ne "$CURRENT_MINOR" ]; then
          PATCH=0
        else
          PATCH=$((PATCH + 1))
        fi

        # Construct the new version
        NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    # - name: Create and Push New Tag
    #   run: |
    #     git tag -a ${{ env.NEW_VERSION }} -m "Release version ${{ env.NEW_VERSION }}"
    #     git push origin ${{ env.NEW_VERSION }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Release Notes
      id: generate_notes
      run: |
        LAST_TAG=${{ env.LATEST_TAG }}
        NEW_TAG=${{ env.NEW_VERSION }}
        
        # Fetch the commit date of the latest tag
        TAG_COMMIT_DATE=$(git log -1 --format=%cI $LAST_TAG 2>/dev/null || echo "No tag found")
        if [ "$TAG_COMMIT_DATE" = "No tag found" ]; then
          echo "Error: Tag $LAST_TAG not found." >&2
          exit 1
        fi
        
        TAG_DATE=$(date -u -d "$TAG_COMMIT_DATE" +%Y-%m-%dT%H:%M:%SZ)
        echo "TAG_DATE=$TAG_DATE" >> $GITHUB_ENV
        
        # Fetch merged PRs since the last tag using GitHub API
        API_URL="https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=master&sort=updated&direction=desc"
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$API_URL")
        
        # Check if the API response is valid
        if [ -z "$RESPONSE" ]; then
          echo "Error: No response from GitHub API." >&2
          exit 1
        fi
        
        # Function to get closed issues for a PR
        get_issues() {
          PR_NUMBER=$1
          ISSUES_API_URL="https://api.github.com/repos/${{ github.repository }}/issues?state=closed&per_page=100"
          ISSUES_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$ISSUES_API_URL")
          if [ -z "$ISSUES_RESPONSE" ]; then
            echo "Error: No response from GitHub issues API." >&2
            exit 1
          fi
          echo "$ISSUES_RESPONSE" | jq -r --arg PR_NUMBER "$PR_NUMBER" '
            .[] | select(.pull_request != null and .pull_request.url | test("pulls/" + $PR_NUMBER)) |
            "- #\(.number) \(.title)"' | sed 's/\\n/\n/g'
        }
        
        # Generate release notes
        RELEASE_NOTES=""
        for pr in $(echo "$RESPONSE" | jq -r --arg TAG_DATE "$TAG_DATE" '.[] | select(.merged_at != null and (.merged_at > $TAG_DATE)) | @base64'); do
          _jq() {
            echo ${pr} | base64 --decode | jq -r ${1}
          }
        
          TITLE=$(_jq '.title')
          BODY=$(_jq '.body // "No description"')
          MERGED_AT=$(_jq '.merged_at')
          PR_NUMBER=$(_jq '.number')
        
          # Get closed issues associated with this PR
          ISSUES=$(get_issues $PR_NUMBER)
        
          # Format the release notes entry
          RELEASE_NOTES+="**$TITLE**\n\n$(echo "$BODY" | sed 's/^/• /')\n\nClosed Issues:\n${ISSUES:-None}\n\nMerged at: $MERGED_AT\n\n---\n\n"
        done
        
        # Handle new lines and special characters
        CLEANED_NOTES=$(echo "$RELEASE_NOTES" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
        
        # Handling empty output
        if [ -z "$CLEANED_NOTES" ]; then
          CLEANED_NOTES="No new PRs since the last tag."
        fi
        
        # Print debug information
        echo -e "LAST_TAG = ${LAST_TAG}"
        echo -e "NEW_TAG = ${NEW_TAG}"
        echo -e "RELEASE_NOTES = ${CLEANED_NOTES}"
        echo -e "LAST_TAG_DATE = ${TAG_DATE}"
        
        echo "RELEASE_NOTES=Release Notes:\n${CLEANED_NOTES}" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - name: Create Release and Upload APK
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: ${{ env.NEW_VERSION }}
    #     files: ./app/build/outputs/apk/release/lost-cities-calculator.apk
    #     body: ${{ env.RELEASE_NOTES }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
